[master]
    host = "localhost"
    port = ":8090"

[cors]
allowed-origins = ["*"]
allowed-methods = ["GET", "POST"]
allowed-headers = ["*"]
exposed-headers = ["*"]

[mysql]
    user = "root"
    password = "mysql"
    database = "test"
    host = "localhost"
    port = "3306"
    table1 = "test"


