[master]
    host = "localhost"
    port = ":8090"

[cors]
allowed-origins = ["*"]
allowed-methods = ["GET", "POST"]
allowed-headers = ["*"]
exposed-headers = ["*"]

[mysql]
    user = "root"
    password = "123456"
    database = "practice1"
    host = "122.51.54.111"
    port = "3306"
    table1 = "person"


