[master]
    host = "localhost"
    port = ":8090"
    setLevel = "debug"

[cors]
allowed-origins = ["*"]
allowed-methods = ["GET", "POST"]
allowed-headers = ["*"]
exposed-headers = ["*"]

[mysql]
    user = "root"
    password = "123456"
    database = "practice1"
    host = "122.51.54.111"
    port = "3306"
    tOne = "home_pages"
    tTwo = "users"

[jwt]
    secret = "asdkjasdhuahqe"
    ExpiresAt = "1"

[log]
    deleteFileOnExit = true
    osName = "./log/logs/"

[wxApp]
    secret = "063177f196709daf7decfd0fd3095565"
    app_id = "wx0ca4b7241f70ea19"